In [1]:
import pandas as pd

### Question 1: Pandas version and getting the data

In [2]:
pd.__version__

'3.0.6'

In [4]:
path = "/workspaces/ZoomML_Homeworks/homework_1/car_fuel_efficiency_2026.csv"
df = pd.read_csv(path)
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

### Question 2: records count
How many records are in the dataset?

In [5]:
len(df)

10000

### Question 3: fuel types
How many fuel types are presented in the dataset?

In [6]:
df["fuel_type"]

0       Gasoline
1         Diesel
2       Gasoline
3       Gasoline
4         Diesel
          ...
9995    Gasoline
9996    Gasoline
9997    Gasoline
9998      Hybrid
9999      Diesel
Name: fuel_type, Length: 10000, dtype: str

In [7]:
df["fuel_type"].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [8]:
print("List of fuel types: ",set(df["fuel_type"])) #another method
num_fuel_types = len(set(df["fuel_type"]))
print("Number of fuel types: ",num_fuel_types)

List of fuel types:  {'Diesel', 'Gasoline', 'Hybrid'}
Number of fuel types:  3

### Question 4: missing values
How many columns in the dataset have missing values?

In [9]:
print(df.columns)
print(len(df.columns))

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')
11

In [10]:
bool_series = df.isna().any()

In [11]:
print("Total number of columns: ", len(df.columns))
print("Total number of columns with missing values: ", bool_series.sum())
#print("Number of columns without missing values: ", len(df.columns)- bool_series.sum())
print("Number of columns without missing values: ", (~bool_series).sum())

Total number of columns:  11
Total number of columns with missing values:  2
Number of columns without missing values:  9

### Question 5: max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [12]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [13]:
asian_cars = df["origin"] == "Asia"
df[asian_cars]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [17]:
asian_fuel_efficiency = df[asian_cars]["fuel_efficiency_mpg"]
print("Maximum fuel efficiency of cars from Asia: ",max(asian_fuel_efficiency))

Maximum fuel efficiency of cars from Asia:  41.2

In [ ]:
#seleziona righe dove fuel_efficiency è maggiore di 28 nelle auto asiatiche, mostra colonne fuel_efficiency,drivetrain,num_doors
#temperature_condition = df["fuel_efficiency_mpg"] > 28
#df[(temperature_condition) & (asian_cars)][["fuel_efficiency_mpg","drivetrain","num_doors"]]

### Question 6: median value of horsepower
1. Find the median value of the horsepower column in the dataset:

In [18]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [19]:
horsepower = df["horsepower"]
med_horse = horsepower.median()
print("Median value of the horsepower column: ", med_horse)

Median value of the horsepower column:  254.0

2. Next, calculate the most frequent value of the same horsepower column:

In [20]:
grouped = df.groupby("horsepower").size()
grouped.reset_index(name = "count")

     horsepower  count
0         171.0      1
1         174.0      1
2         175.0      1
3         178.0      1
4         181.0      4
..          ...    ...
148       328.0      1
149       329.0      3
150       330.0      1
151       332.0      3
152       334.0      2

[153 rows x 2 columns]

In [21]:
print(grouped.idxmax(), grouped.max())

252.0 174

In [22]:
most_frequent_horse = grouped.idxmax()
print("Most frequent value of horsepower column: ", most_frequent_horse)

Most frequent value of horsepower column:  252.0

3. Use the 'fillna' method to fill the missing values in the horsepower column with the most frequent value from the previous step:

In [23]:
df["new_horsepower"] = df["horsepower"].fillna(most_frequent_horse)
print(df["new_horsepower"].hasnans)
print(df["horsepower"].hasnans)

False
True

4. Now, calculate the median value of horsepower once again:

In [24]:
new_horsepower = df["new_horsepower"]
new_med_horse = new_horsepower.median()

In [25]:
print("Old median horsepower: ", med_horse)
print("New median horsepower: ", new_med_horse)
print("Difference between the two values: ", med_horse-new_med_horse)

Old median horsepower:  254.0
New median horsepower:  252.0
Difference between the two values:  2.0

### Question 7: sum of weights
1. Select all the cars from Asia

In [27]:
df[asian_cars]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg,new_horsepower
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5,267.0
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8,250.0
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9,251.0
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8,252.0
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4,226.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4,256.0
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0,266.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4,236.0
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1,257.0
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0,244.0

2. Select only columns 'vehicle_weight' and 'model_year'

In [28]:
df[asian_cars][["vehicle_weight","model_year"]]

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

3. Select the first 7 values

In [29]:
df[asian_cars][["vehicle_weight","model_year"]].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

7. Get the underlying NumPy array. Let's call it X.

In [30]:
import numpy as np

In [34]:
X = (
    df
    [asian_cars]
    [["vehicle_weight","model_year"]]
    .head(7)
    .to_numpy() 
    )
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [37]:
XTX = X.T@X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

6. Invert XTX.

In [40]:
m = np.linalg.inv(XTX)
m

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

In [39]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [44]:
w = (m@X.T)@ y
w

array([0.13644777, 0.2327492 ])

9. What's the sum of all the elements of the result?

In [45]:
print("Sum of the element of w: ", w.sum())

Sum of the element of w:  0.36919696904925486